#include "TestPrinters.h"
#include <bcos-evm/opstack/OpForkSchedule.h>
#include <bcos-evm/opstack/OpPrecompiles.h>
#include <bcos-utilities/DataConvertUtility.h>
#include <json/json.h>
#include <boost/test/unit_test.hpp>
#include <filesystem>
#include <fstream>

using namespace bcos::evm::opstack;

BOOST_AUTO_TEST_SUITE(OpPrecompilesSuite)

BOOST_AUTO_TEST_CASE(P256VerifyGasOverrideAndAddressExtension)
{
    const evmc::address addr{0x100};
    const auto& overrides = isthmusPrecompileOverrides();
    BOOST_CHECK(overrides.contains(addr));
    const auto* entry = overrides.find(addr);
    BOOST_REQUIRE((entry) != nullptr);
    BOOST_CHECK_EQUAL(entry->gas_cost_override, 3450);
    BOOST_CHECK_EQUAL(entry->max_input_size, 0U);
}

BOOST_AUTO_TEST_CASE(Bn256PairingInputLimitNoGasOverride)
{
    const evmc::address addr{0x08};
    const auto& overrides = isthmusPrecompileOverrides();
    BOOST_CHECK(overrides.contains(addr));
    const auto* entry = overrides.find(addr);
    BOOST_REQUIRE((entry) != nullptr);
    BOOST_CHECK_EQUAL(entry->max_input_size, 112687U);
    BOOST_CHECK_LT(entry->gas_cost_override, 0);
}

BOOST_AUTO_TEST_CASE(BlsMsmPairingInputLimits)
{
    const auto& overrides = isthmusPrecompileOverrides();

    const evmc::address g1msm{0x0c};
    BOOST_CHECK(overrides.contains(g1msm));
    const auto* g1Entry = overrides.find(g1msm);
    BOOST_REQUIRE((g1Entry) != nullptr);
    BOOST_CHECK_EQUAL(g1Entry->max_input_size, 513760U);
    BOOST_CHECK_LT(g1Entry->gas_cost_override, 0);

    const evmc::address g2msm{0x0e};
    BOOST_CHECK(overrides.contains(g2msm));
    const auto* g2Entry = overrides.find(g2msm);
    BOOST_REQUIRE((g2Entry) != nullptr);
    BOOST_CHECK_EQUAL(g2Entry->max_input_size, 488448U);
    BOOST_CHECK_LT(g2Entry->gas_cost_override, 0);

    const evmc::address pairing{0x0f};
    BOOST_CHECK(overrides.contains(pairing));
    const auto* pairingEntry = overrides.find(pairing);
    BOOST_REQUIRE((pairingEntry) != nullptr);
    BOOST_CHECK_EQUAL(pairingEntry->max_input_size, 235008U);
    BOOST_CHECK_LT(pairingEntry->gas_cost_override, 0);
}

BOOST_AUTO_TEST_CASE(ForkConfigWiresPrecompiles)
{
    BOOST_CHECK_EQUAL(isthmusConfig().precompiles, &isthmusPrecompileOverrides());
}

BOOST_AUTO_TEST_CASE(JovianLimitsStricterThanIsthmus)
{
    const auto* j08 = jovianPrecompileOverrides().find(evmc::address{0x08});
    const auto* i08 = isthmusPrecompileOverrides().find(evmc::address{0x08});
    BOOST_REQUIRE((j08) != nullptr);
    BOOST_REQUIRE((i08) != nullptr);
    BOOST_CHECK_EQUAL(j08->max_input_size, 81984u);
    BOOST_CHECK_LT(j08->max_input_size, i08->max_input_size);

    BOOST_CHECK_EQUAL(
        jovianPrecompileOverrides().find(evmc::address{0x0c})->max_input_size, 288960u);
    BOOST_CHECK_EQUAL(
        jovianPrecompileOverrides().find(evmc::address{0x0e})->max_input_size, 278784u);
    BOOST_CHECK_EQUAL(
        jovianPrecompileOverrides().find(evmc::address{0x0f})->max_input_size, 156672u);
    BOOST_CHECK_EQUAL(jovianConfig().precompiles, &jovianPrecompileOverrides());
    BOOST_CHECK_EQUAL(karstConfig().precompiles, &karstPrecompileOverrides());
    BOOST_CHECK(karstConfig().precompiles != jovianConfig().precompiles);
}

// Karst's precompile table judged by an EXTERNAL implementation (op-revm), not by its own
// literals. The oracle JSON is a tracked contract regenerated by
// tools/op-revm-oracle/extract.sh from the pinned checkout; the path is resolved from this
// translation unit so no CMake definition is needed.
BOOST_AUTO_TEST_CASE(KarstTableMatchesOpRevmOracle)
{
    auto const oraclePath = std::filesystem::path(__FILE__).parent_path() / "op_revm_oracle.json";
    BOOST_REQUIRE_MESSAGE(std::filesystem::exists(oraclePath),
        "missing oracle contract at " << oraclePath.string()
                                      << " — regenerate with tools/op-revm-oracle/extract.sh");
    Json::Value oracle;
    {
        std::ifstream in(oraclePath);
        BOOST_REQUIRE_MESSAGE(
            Json::Reader{}.parse(in, oracle, false), "cannot parse " << oraclePath.string());
    }
    BOOST_TEST_MESSAGE("op-revm oracle revision: " << oracle["source"]["revision"].asString());

    const auto& table = karstPrecompileOverrides();
    const auto* bn254 = table.find(evmc::address{0x08});
    const auto* p256 = table.find(evmc::address{0x100});
    const auto* g1 = table.find(evmc::address{0x0c});
    const auto* g2 = table.find(evmc::address{0x0e});
    const auto* pair = table.find(evmc::address{0x0f});
    BOOST_REQUIRE(bn254 != nullptr);
    BOOST_REQUIRE(p256 != nullptr);
    BOOST_REQUIRE(g1 != nullptr);
    BOOST_REQUIRE(g2 != nullptr);
    BOOST_REQUIRE(pair != nullptr);

    BOOST_CHECK_EQUAL(bn254->max_input_size,
        static_cast<std::size_t>(oracle["bn254_pairing_max_input_size"].asUInt64()));
    BOOST_CHECK_EQUAL(g1->max_input_size,
        static_cast<std::size_t>(oracle["bls_g1_msm_max_input_size"].asUInt64()));
    BOOST_CHECK_EQUAL(g2->max_input_size,
        static_cast<std::size_t>(oracle["bls_g2_msm_max_input_size"].asUInt64()));
    BOOST_CHECK_EQUAL(pair->max_input_size,
        static_cast<std::size_t>(oracle["bls_pairing_max_input_size"].asUInt64()));
    // BLS caps are inherited from Jovian: op-revm's karst() clones jovian() and swaps only
    // modexp/P256/bn254-pair, so the Karst table must equal Jovian's for those three addresses.
    const auto* jovianG1 = jovianPrecompileOverrides().find(evmc::address{0x0c});
    const auto* jovianG2 = jovianPrecompileOverrides().find(evmc::address{0x0e});
    const auto* jovianPair = jovianPrecompileOverrides().find(evmc::address{0x0f});
    const auto* jovianBn254 = jovianPrecompileOverrides().find(evmc::address{0x08});
    BOOST_REQUIRE(jovianG1 != nullptr);
    BOOST_REQUIRE(jovianG2 != nullptr);
    BOOST_REQUIRE(jovianPair != nullptr);
    BOOST_REQUIRE(jovianBn254 != nullptr);
    BOOST_CHECK_EQUAL(jovianG1->max_input_size, g1->max_input_size);
    BOOST_CHECK_EQUAL(jovianG2->max_input_size, g2->max_input_size);
    BOOST_CHECK_EQUAL(jovianPair->max_input_size, pair->max_input_size);
    if (oracle["p256verify_gas"].isNull())
    {
        // Minimal read set recorded in the design doc: revm-precompile <version>/src/secp256r1.rs.
        BOOST_TEST_MESSAGE(
            "p256verify_gas not resolved from the local registry; minimal read set "
            "= revm-precompile "
            << oracle["revm_precompile_version"].asString() << "/src/secp256r1.rs");
    }
    else
    {
        BOOST_CHECK_EQUAL(
            p256->gas_cost_override, static_cast<int64_t>(oracle["p256verify_gas"].asInt64()));
    }
    // The bn254 pair must be the ONE address whose Karst value differs from Jovian's; if that
    // ever stops being true, the Karst row stopped being a real fork delta.
    BOOST_CHECK_LT(bn254->max_input_size, jovianBn254->max_input_size);
}
BOOST_AUTO_TEST_SUITE_END()
